---
- name: Deploy webservers
  hosts: webservers
  become: yes
  vars:
    http_port: 8080
    
  tasks:
    - name: Install Python3 and pip
      apt:
        name: 
          - python3
          - python3-pip
        state: present
        update_cache: yes
      
    - name: Install required packages
      apt:
        name:
          - nginx
        state: present

    - name: Create nginx sites-available configuration
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: restart nginx

    - name: Create web content directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Deploy index page
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        mode: '0644'
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
